import turtle as te
mypen = te.Pen()
te.hideturtle()

# 手柄部分
te.forward(-400)
te.pensize(30)
te.pencolor("silver")
te.forward(30)
te.pencolor("black")
te.forward(20)
te.pencolor("black")
te.forward(20)
te.pencolor("black")
te.forward(20)
te.pencolor("black")
te.forward(20)
te.pencolor("silver")
te.forward(40)
te.pencolor("black")
te.forward(50)
te.pencolor("silver")
te.forward(60)

#剑身主体
te.pencolor("deepskyblue")
te.pensize(32)
te.forward(600)
te.pencolor("lightskyblue")
te.pensize(28)
te.forward(-600)
te.pencolor("skyblue")
te.pensize(24)
te.forward(600)
te.pencolor("paleturquoise")
te.pensize(20)
te.forward(-600)
te.pensize(16)
te.pencolor("lightcyan")
te.forward(600)
te.pencolor("azure")
te.pensize(12)
te.forward(-600)
te.pensize(8)
te.pencolor("ghostwhite")
te.forward(600)
te.pensize(8)
te.pencolor("white")
te.forward(-600)

#光晕部分
te.pencolor("azure")
te.forward(600)
te.pencolor("lightcyan")
te.forward(-600)


te.done()