import turtle as te
mypen = te.Pen()

mypen.pensize(150)
mypen.forward(200)

mypen.pensize(80)
mypen.pencolor("limegreen")
mypen.forward(0)
mypen.pensize(0)
mypen.forward(-40)
mypen.pencolor("black")
mypen.forward(-60)
mypen.pensize(80)
mypen.pencolor("gold")
mypen.forward(0)
mypen.pensize(0)
mypen.forward(-40)
mypen.pencolor("black")
mypen.forward(-60)
mypen.pensize(80)
mypen.pencolor("orangered")
mypen.forward(0)
mypen.hideturtle()
te.done()